f

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -99,8 +99,11 @@ jobs:
           assignees: Glatzel
           draft: true
   build-result:
-    if: ${{ github.event_name == 'pull_request' && (success() || needs.dispatch.outputs.matrix == '')}}
+    if: ${{ github.event_name == 'pull_request' && !cancelled()}}
     needs: [rattler-build, dispatch]
     runs-on: ubuntu-slim
     steps:
-      - run: echo "success"
+      - if: ${{success() || needs.dispatch.outputs.matrix == ''}}
+        run: echo "success"
+      - if: ${{!(success() || needs.dispatch.outputs.matrix == '')}}
+        run: echo "fail" && exit 1
